name: W5E5_regrid_env
channels:
  - conda-forge
dependencies:
  - python=3.7
  - pip>=10.0
  - numpy==1.21.5
  - scipy==1.7.3
  - pandas==1.3.5
  - xarray==0.20.2
  - dask==2021.10.0
  - netCDF4>=1.5.8
  - ESMPy>=8.2.0
  - xesmf==0.6.3
  - rioxarray>=0.9.1
